services:
  backend:
    network_mode: host
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    volumes:
      - app_data:/app 
  frontend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
volumes:
  app_data: {} 