services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    volumes:
      - ./backend/:/app
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules